//
//  XRInstrument.h
//  MacDemoNew
//
//  Created by yangfl on 2016/12/28.
//  Copyright © 2016年 szzc. All rights reserved.
//

#import <Foundation/Foundation.h>
/*
@interface XRInstrument : NSObject

@end
 */


/*
@interface XRInstrument : NSObject <XRLazyKVOResponder, NSCoding, XRInspectorSource, XRTemplateProtocol, XRSourceCommentProvider, NSOutlineViewDelegate, NSOutlineViewDataSource>
{
    PFTInstrumentType *_type;
    XRTrace *_trace;
    int _graphType;
    NSMutableArray *_runList;
    BOOL _isEndingCommand;
    BOOL _isDisplayingContext;
    BOOL _ignoreContextChanges;
    NSObject *_sourceView;
    NSObject *_consoleView;
    long long _selectedBrush;
    id <XRBrushDataSource> _cachedBrushDataSource;
    XRIntKeyedDictionary *_tableSpecsByID;
    NSSet *_tableSwitchNames;
    NSMutableSet *_schemasForNextRun;
    id <XRInstrumentViewController> _viewController;
    NSDictionary *_viewControllerStateFromTemplate;
    BOOL _isInvalid;
    int _states[6];
    XRRun *_run;
    unsigned long long _selectedRunIndex;
    NSString *_uuid;
    NSMutableArray *_permittedContexts;
    struct XRTimeRange _recordedDataTimeRange;
    PFTInstrumentCommand *_currentCommand;
    BOOL _addedAdHoc;
    int _commandType;
    PFTProcess *_commandTarget;
    id _targetDevice;
    BOOL _isSelected;
    double _generalScaleFactor;
    unsigned int _masterDeckUnits;
    unsigned int _detailDeckUnits;
    double _peakTrackValue;
    NSMutableDictionary *_peakTrackValuePerGraph;
    id _graphedDataTarget;
    BOOL _requiresControlBand;
    BOOL _initializedSwitchAttributes;
    BOOL _isSettingDetailView;
    NSMutableArray *_navigationStack;
    NSArrayController *_navigationStackController;
    NSMutableDictionary *_detailViewPreferences;
    float _analysisProgress;
    NSRecursiveLock *_analysisProgressLock;
    XRInstrumentControlState *_recordingControlState;
    XRInstrumentControlState *_displayControlState;
    XRLazyKVOAdapter *_kvoAdapter;
}

+ (id)dataElementWithIdentifier:(id)arg1 title:(id)arg2 editable:(BOOL)arg3 enabledWhileRunning:(BOOL)arg4 object:(id)arg5 target:(id)arg6 keyPaths:(id)arg7;
+ (void)initialize;
@property(readonly, nonatomic) id recordingControlState; // @synthesize recordingControlState=_recordingControlState;
@property(readonly, nonatomic) XRInstrumentControlState *displayControlState; // @synthesize displayControlState=_displayControlState;
- (void).cxx_destruct;
- (id)userInterfacePlan;
- (void)focusOnSummary:(id)arg1;
- (void)setViewController:(id)arg1;
- (id)viewController;
- (id)provideSourceAnnotationsForQuery:(id)arg1;
- (void)setAnalysisProgress:(float)arg1;
- (float)analysisProgress;
- (id)strategyIdentifiersSupported;
- (void)refreshSummaries;
- (BOOL)needsSummaryView;
- (id)eventDescriptorForIdentifier:(id)arg1;
- (id)preferenceForViewWithName:(id)arg1;
- (void)setViewPreferenceForName:(id)arg1 preference:(id)arg2;
- (id)dataMiningMenu;
- (BOOL)supportsDataMining;
- (id)documentUUID;
- (id)dataElementsForInspector:(id)arg1;
- (void)inspectorDismissed:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)resetTargetDeviceProperties;
- (BOOL)supportsRecordingOption:(id)arg1 forDevice:(id)arg2;
- (BOOL)hasCustomStateDisplayDescription;
- (id)stateDisplayDescription;
- (id)reasonForNotSupportingDevice:(id)arg1;
- (BOOL)isDeviceSupported:(id)arg1;
- (id)deviceStateDescription:(id)arg1;
- (void)setTargetDevice:(id)arg1;
- (id)targetDevice;
- (void)clearContextForContext:(id)arg1;
- (void)popDataContext:(id)arg1 forContext:(id)arg2;
- (void)pushDataContext:(id)arg1 forContext:(id)arg2;
- (id)dataContextForContext:(id)arg1;
- (void)popNavigationItem:(id)arg1;
- (void)pushNavigationItem:(id)arg1;
- (void)clearAllNavigationItems;
- (id)navigationStackController;
- (id)navigationStack;
- (void)setSymbolSelected:(id)arg1 withCallTreeInformation:(id)arg2;
- (id)sourceView;
- (BOOL)supportsSource;
- (BOOL)viewAsCallTree;
- (void)setViewAsCallTree:(BOOL)arg1;
- (BOOL)supportsCallTree;
- (id)errorMessage;
- (void)setErrorMessage:(id)arg1;
- (void)setErrorMessage:(id)arg1 inSection:(id)arg2;
- (void)setErrorMessage:(id)arg1 inSection:(id)arg2 withHelpReference:(id)arg3;
- (BOOL)addedAdHoc;
- (void)setAddedAdHoc:(BOOL)arg1;
- (BOOL)useLegacyBrush;
- (BOOL)detailViewRequiresScrollView:(id)arg1;
- (id)allowedTriggerActions;
- (void)setDetailDeckUnits:(unsigned int)arg1;
- (unsigned int)detailDeckUnits;
- (void)setMasterDeckUnits:(unsigned int)arg1;
- (unsigned int)masterDeckUnits;
- (void)setGraphType:(int)arg1;
- (int)graphType;
- (void)resetPeakValues;
- (double)peakTrackValueForGraphAtIndex:(long long)arg1;
- (void)setPeakTrackValue:(double)arg1 forGraphAtIndex:(long long)arg2;
- (double)peakTrackValue;
- (void)setPeakTrackValue:(double)arg1;
- (void)_refreshTrackView;
- (void)setDetailViewScaleValue:(double)arg1;
- (double)detailViewScaleValue;
- (void)setSelected:(BOOL)arg1;
- (BOOL)isSelected;
- (id)_selectedSearchContext;
- (id)_searchContexts;
- (void)_filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;
- (void)updateContext:(id)arg1 delayed:(BOOL)arg2;
- (void)updateContext:(id)arg1;
- (id)dataElementsForTargetCommands;
- (id)dataElementsForContext:(id)arg1;
- (id)_dataElementsForContext:(id)arg1;
- (void)_setNeedsSetupDataElementRefresh;
- (void)_setNeedsSearchDataElementRefresh;
- (void)_setNeedsDetailDataElementRefresh;
- (void)_setNeedsEventDataElementRefresh;
- (void)_setNeedsInstrumentDataElementRefresh;
- (void)freeSwitchAttributes;
- (void)initializeSwitchAttributes;
- (id)displaySwitchDescriptors;
- (id)recordingSwitchDescriptors;
- (id)recordingControlMetaUIDescriptors;
- (BOOL)initialValueForSwitch:(id)arg1;
- (void)postCoreHighlightNotificationForThreadID:(unsigned long long)arg1 context:(id)arg2;
- (void)postThreadHighlightNotificationForThreadID:(unsigned long long)arg1 context:(id)arg2;
- (void)halfTick:(id)arg1;
- (BOOL)requiresHalfTickNotification;
- (void)_tick:(id)arg1;
- (void)tick:(id)arg1;
- (BOOL)requiresTickNotification;
- (void)setCurrentBrushName:(id)arg1;
- (id)currentBrushName;
- (id)brushNames;
- (id)defaultBrushName;
- (void)resetBrushState;
- (struct XRTimeRange)recordedDataTimeRange;
- (id)cachedBrushDataSource;
- (void)updateTrackView;
- (void)updateTrackView:(BOOL)arg1;
- (void)updateTrackViewInRange:(struct XRTimeRange)arg1;
- (int)deckUnitsForHostType:(int)arg1;
- (double)trackHeightForHostType:(int)arg1;
- (void)setNeedsTrackRefresh;
- (id)createTrackSegment;
- (void)addTrackSegment:(BOOL)arg1;
- (id)runFromRunNumber:(long long)arg1;
- (id)selectedRun;
- (unsigned long long)selectedRunIndex;
- (BOOL)setSelectedRunIndex:(unsigned long long)arg1;
- (void)setShowRunsInUI:(BOOL)arg1;
- (BOOL)showRunsInUI;
- (BOOL)showRuns;
- (id)currentRun;
- (id)allRuns;
- (id)displayNameForRun:(id)arg1;
- (void)deleteRun:(id)arg1;
- (void)setCurrentRun:(id)arg1;
- (id)createRun;
- (BOOL)canAddFlag;
- (BOOL)canReplay;
- (BOOL)canRun;
- (BOOL)targetPaused;
- (void)setTargetPaused:(BOOL)arg1;
- (void)disableRecording;
- (void)enableRecording;
- (BOOL)recordingEnabled;
- (void)setRecordingEnabled:(BOOL)arg1;
- (void)notifyStateChanged;
- (void)toggleAttribute:(int)arg1 withinHost:(id)arg2;
- (void)setState:(int)arg1 forAttribute:(int)arg2;
- (int)stateForAttribute:(int)arg1;
- (BOOL)supportsAttribute:(int)arg1 inHostType:(int)arg2;
- (id)createMenuForAttribute:(int)arg1 inHostType:(int)arg2;
- (void)_selectTrackBrush:(id)arg1;
- (BOOL)hasMenuForAttribute:(int)arg1 inHostType:(int)arg2;
- (void)stopRecording;
- (void)startRecording;
- (void)prepareToRecord;
- (void)initializeRunForCommand:(id)arg1;
- (BOOL)verifyEnvironment:(id)arg1 arguments:(id)arg2 instruments:(id)arg3 error:(id *)arg4;
- (BOOL)configureEnvironment:(id)arg1 arguments:(id)arg2 instruments:(id)arg3 error:(id *)arg4;
- (void)setCurrentCommand:(id)arg1;
- (id)currentCommand;
- (void)endCommand:(id)arg1;
- (void)suspendDataCollection;
- (void)willEndCommand:(id)arg1;
- (void)_endTraceOnProcessFailure;
- (void)startCommand:(id)arg1;
- (void)cancelCommand:(id)arg1;
- (BOOL)acceptCommand:(id)arg1;
- (void)didLaunchTarget:(id)arg1;
- (void)willLaunchTarget:(id)arg1;
- (int)minimumAuthorizationRequirement;
- (void)targetTerminated:(id)arg1;
- (void)observeTargets:(BOOL)arg1;
- (id)target;
- (void)setTarget:(id)arg1;
- (id)coreStrategyController;
- (id)threadStrategyController;
- (void)setTrace:(id)arg1;
- (id)trace;
- (int)targetProcessIdentifier;
- (int)trueTargetType;
- (int)commandTypeViaUI;
- (void)setCommandTypeViaUI:(int)arg1;
- (int)defaultTargetType;
- (id)reasonForNotSupportingRecordingOptions:(id)arg1;
- (BOOL)supportsMode:(id)arg1;
- (BOOL)supportsTargetType:(int)arg1;
- (int)targetType;
- (void)setTargetType:(int)arg1;
- (id)uuid;
- (id)contextMenuTitleForColumnWithIdentifier:(id)arg1;
- (id)panelName;
- (id)displayName;
- (void)setDisplayContext:(id)arg1 visible:(BOOL)arg2;
- (BOOL)isDisplayContextVisible:(id)arg1;
- (BOOL)displayEnabled;
- (id)_fixupLoadedBrushName:(id)arg1;
- (void)restoreFromTraceTemplateData:(id)arg1;
- (id)traceTemplateData;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (int)hostType;
- (void)setType:(id)arg1;
- (id)type;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)awakeFromTemplate;
- (void)invalidate;
- (void)dealloc;
- (id)initWithType:(id)arg1;
- (BOOL)needsKTraceToRecord;
- (id)extension;
- (id)initWithExtension:(id)arg1;
- (void)overrideCoreExtensionsURLsForNextRun:(id)arg1;
- (void)overrideDynamicTableRequirementsForNextRun:(id)arg1 withAdditionalSchemas:(id)arg2;
- (id)additionalColumnsForNextRun:(id)arg1 finalSchemaName:(id)arg2;
- (void)overrideDisplayedTableList:(id)arg1;
- (id)dtacExtensionsForNextRun;
- (id)switchesReferencedInTableRequirements;
- (unsigned int)tableIDForSpec:(id)arg1 runNumber:(long long)arg2;
- (void)updateAnalysisCoreForNextRun;
- (void)removeAllCoreRequirementsForNextRun;
- (id)tableSpecsByTableIDForNextRun;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end
*/
